src/Entity/Scenario.php
<?php

namespace App\Entity;

use App\Repository\ScenarioRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Get;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Entity(repositoryClass: ScenarioRepository::class)]
    #[ApiResource(
        normalizationContext: ['groups' => ['owner:read']],
        stateless: false,
        operations: [
            new GetCollection(),
            new Get(),
        ],
    )]
class Scenario
{

    public const STATUS_CREATED = 'created';
    public const STATUS_AWARDED = 'awarded';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 2, scale: 0, nullable: false)]
    private ?string $level = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: false)]
    private ?\DateTime $date = null;

    #[ORM\Column(type: Types::BLOB, nullable: true)]
    private $img;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: false)]
    private ?string $post_link = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: false)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'scenarios')]
    private ?User $game_master = null;

    #[Groups(['owner:read'])]
    #[SerializedName('gamemaster')]
    public function getGameMasterId(): ?int
    {
        return $this->game_master ? $this->game_master->getId() : null;
    }

    /**
     * @var Collection<int, Token>
     */
    #[ORM\OneToMany(targetEntity: Token::class, mappedBy: 'scenario')]
    private Collection $tokens;

    /**
     * @var Collection<int, Character>
     */
    #[ORM\ManyToMany(targetEntity: Character::class, inversedBy: 'scenarios')]
    private Collection $characters;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?bool $editable = null;

    public function __construct()
    {
        $this->tokens = new ArrayCollection();
        $this->characters = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->level;
    }

    public function setLevel(string $level): static
    {
        $this->level = $level;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getImg()
    {
        return $this->img;
    }

    public function setImg($img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getPostLink(): ?string
    {
        return $this->post_link;
    }

    public function setPostLink(string $post_link): static
    {
        $this->post_link = $post_link;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getGameMaster(): ?User
    {
        return $this->game_master;
    }

    public function setGameMaster(?User $game_master): static
    {
        $this->game_master = $game_master;

        return $this;
    }

    /**
     * @return Collection<int, Token>
     */
    public function getTokens(): Collection
    {
        return $this->tokens;
    }

    public function addToken(Token $token): static
    {
        if (!$this->tokens->contains($token)) {
            $this->tokens->add($token);
            $token->setScenario($this);
        }

        return $this;
    }

    public function removeToken(Token $token): static
    {
        if ($this->tokens->removeElement($token)) {
            // set the owning side to null (unless already changed)
            if ($token->getScenario() === $this) {
                $token->setScenario(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Character>
     */
    public function getCharacters(): Collection
    {
        return $this->characters;
    }

    public function addCharacter(Character $character): static
    {
        if (!$this->characters->contains($character)) {
            $this->characters->add($character);
        }

        return $this;
    }

    public function removeCharacter(Character $character): static
    {
        $this->characters->removeElement($character);

        return $this;
    }

    public function isEditable(): ?bool
    {
        return $this->editable;
    }

    public function setEditable(?bool $editable): static
    {
        $this->editable = $editable;

        return $this;
    }

}

src/Entity/Token.php
<?php

namespace App\Entity;

use App\Repository\TokenRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Get;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Entity(repositoryClass: TokenRepository::class)]
    #[ApiResource(
        normalizationContext: ['groups' => ['owner:read']],
        stateless: false,
        operations: [
            new GetCollection(),
            new Get(),
        ],
    )]
class Token
{
    public const STATUS_PUBLISHED = 'created';
    public const STATUS_AWARDED = 'awarded';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;
    
    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: false)]
    private ?string $type = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?int $usage_rate = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?int $delta_pr = null;

    #[Groups(['owner:read'])]
    private ?int $delta_pr_from_level = null;

    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?Scenario $scenario = null;

    #[Groups(['owner:read'])]
    #[SerializedName('scenario')]
    public function getScenarioId(): ?int
    {
        return $this->scenario ? $this->scenario->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?Character $character = null;

    #[Groups(['owner:read'])]
    #[SerializedName('character')]
    public function getCharacterId(): ?int
    {
        return $this->character ? $this->character->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?\DateTime $date_of_reception = null;

    #[Groups(['owner:read'])]
    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?User $owner_user = null;

    #[Groups(['owner:read'])]
    #[SerializedName('owner_user')]
    public function getOwnerId(): ?int
    {
        return $this->owner_user ? $this->owner_user->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $totalRate = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $totalPr = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getUsageRate(): ?int
    {
        return $this->usage_rate;
    }

    public function setUsageRate(int $usage_rate): static
    {
        $this->usage_rate = $usage_rate;

        return $this;
    }

    public function getDeltaPr(): ?int
    {
        return $this->delta_pr;
    }

    public function setDeltaPr(int $delta_pr): static
    {
        $this->delta_pr = $delta_pr;

        return $this;
    }

    public function getDeltaPrFromLevel(): ?int
    {
        return $this->delta_pr_from_level;
    }

    public function setDeltaPrFromLevel(int $delta_pr_from_level): static
    {
        $this->delta_pr_from_level = $delta_pr_from_level;

        return $this;
    }

    public function getScenario(): ?Scenario
    {
        return $this->scenario;
    }

    public function setScenario(?Scenario $scenario): static
    {
        $this->scenario = $scenario;

        return $this;
    }

    public function getCharacter(): ?Character
    {
        return $this->character;
    }

    public function setCharacter(?Character $character): static
    {
        $this->character = $character;

        return $this;
    }

    public function getDateOfReception(): ?\DateTime
    {
        return $this->date_of_reception;
    }

    public function setDateOfReception(\DateTime $date_of_reception): static
    {
        $this->date_of_reception = $date_of_reception;

        return $this;
    }

    public function getOwnerUser(): ?User
    {
        return $this->owner_user;
    }

    public function setOwnerUser(?User $owner_user): static
    {
        $this->owner_user = $owner_user;

        return $this;
    }

    public function getTotalRate(): ?string
    {
        return $this->totalRate;
    }

    public function setTotalRate(string $totalRate): static
    {
        $this->totalRate = $totalRate;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getTotalPr(): ?string
    {
        return $this->totalPr;
    }

    public function setTotalPr(?string $totalPr): static
    {
        $this->totalPr = $totalPr;

        return $this;
    }
}

src/Controller/ScenarioController.php
<?php

namespace App\Controller;

use App\Entity\Character;
use App\Entity\Scenario;
use App\Entity\Token;
use App\Form\ScenarioType;
use App\Repository\CharacterRepository;
use App\Repository\ScenarioRepository;
use App\Repository\TokenRepository;
use App\Service\WBLService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/scenario')]
final class ScenarioController extends AbstractController
{
    #[Route(name: 'app_scenario_index', methods: ['GET'])]
    public function index(ScenarioRepository $scenarioRepository): Response
    {
        return $this->render('scenario/index.html.twig', [
            'scenarios' => $scenarioRepository->findAll(),
        ]);
    }

    #[IsGranted('ROLE_GAMEMASTER'), Route('/new', name: 'app_scenario_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $scenario = new Scenario();
        $form = $this->createForm(ScenarioType::class, $scenario);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $scenario->setStatus(Scenario::STATUS_CREATED);

            $scenario->setGameMaster($this->getUser());

            $token = new Token();
            $token->setScenario($scenario);
            $token->setOwnerUser($this->getUser());
            $token->setTotalRate(150);
            $token->setDeltaPr(150);

            $token->setType("MJ");

            $scenario->addToken($token);
            $entityManager->persist($token);

            $scenario->addToken($token);

            $entityManager->persist($scenario);
            $entityManager->flush();

            return $this->redirectToRoute('app_scenario_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('scenario/new.html.twig', [
            'scenario' => $scenario,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_scenario_show', methods: ['GET'])]
    public function show(Scenario $scenario, WBLService $wBLService): Response
    {
        foreach ($scenario->getTokens() as $token) {
            if ($token->getType() == "MJ") {
                continue;
            }
            $token->setDeltaPrFromLevel(
                $wBLService->rewardExtraPR($scenario->getLevel(), $token->getCharacter()->getLevel()));
        }

        return $this->render('scenario/show.html.twig', [
            'scenario' => $scenario,
        ]);
    }

    #[IsGranted('edit', subject: 'scenario'), Route('/{id}/edit', name: 'app_scenario_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Scenario $scenario, EntityManagerInterface $entityManager, 
        TokenRepository $tokenRepository, ScenarioRepository $scenarioRepository, CharacterRepository $characterRepository,
        WBLService $wBLService): Response
    {
        $form = $this->createForm(ScenarioType::class, $scenario);
        $form->handleRequest($request);

        foreach ($scenario->getTokens() as $token) {

            if ($token->getType() == "MJ") {
                continue;
            }
            $token->setDeltaPrFromLevel(
                $wBLService->rewardExtraPR($scenario->getLevel(), $token->getCharacter()->getLevel()));
        }

        if ($form->isSubmitted() && $form->isValid()) {

            $characters = $scenarioRepository->findCharactersNotInScenario($scenario);

            if ($request->request->has('addToken')) {

                $character = $characterRepository->find($request->request->get('addToken'));

                $token = new Token();
                $token->setScenario($scenario);
                $token->setCharacter($character);
                $token->setTotalRate(100);
                $token->setDeltaPr(100);

                $token->setType("PJ");

                $scenario->addToken($token);
                $entityManager->persist($token);
            } 

            if ($request->request->has('removeToken')) {

                $token = $tokenRepository->find( $request->request->get('removeToken'));
                
                if ($scenario->getTokens()->contains($token)) {
                    $scenario->removeToken($token);
                    $entityManager->remove($token);
                }
                        
            }
            
            $entityManager->flush();

            
            return $this->redirectToRoute('app_scenario_edit', ['id' => $scenario->getId()]);
        }

        $characters = $scenarioRepository->findCharactersNotInScenario($scenario);

        return $this->render('scenario/edit.html.twig', [
            'scenario' => $scenario,
            'characters' => $characters,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_scenario_delete', methods: ['POST'])]
    public function delete(Request $request, Scenario $scenario, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$scenario->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($scenario);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_scenario_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/award/{id}', name: 'app_scenario_award', methods: ['POST'])]
    public function awardToken(Request $request, Scenario $scenario, EntityManagerInterface $entityManager, WBLService $wBLService): Response
    {
        $scenario->setStatus(Scenario::STATUS_AWARDED);

        foreach ($scenario->getTokens() as $token) {
            $totalPr = 0;
            if ($token->getType() == "PJ") {
                $characterLevel = $token->getCharacter()->getLevel();
                $tokenLevel = $token->getScenario()->getLevel();

                $rewardExtraPr = $wBLService->rewardExtraPR($tokenLevel, $characterLevel);
                
                $totalPr = $token->getDeltaPr() + $rewardExtraPr; 
            } elseif ($token->getType() == "MJ") {
                $totalPr = $token->getDeltaPr();
            }

            $token->setTotalPr(max(0, $totalPr));

            $token->setDateOfReception(new \DateTime());
            $token->setName($scenario->getName());
            $token->setUsageRate($token->getTotalRate());  
            $token->setStatus(Token::STATUS_AWARDED);
        }
        
        $entityManager->flush();

        return $this->redirectToRoute('app_scenario_show', ['id' => $scenario->getId()], Response::HTTP_SEE_OTHER);
    }

}

templates/scenario/_delete_form.html.twig
<form method="post" action="{{ path('app_scenario_delete', {'id': scenario.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ scenario.id) }}">
    <button class="btn">Delete</button>
</form>

templates/scenario/_edit_form.html.twig
{{ form_start(form) }}

    <table class="table">
        <tbody>
            <tr>
                <th>Name</th>
                <td>{{ scenario.name }}</td>
                <td>{{ form_widget(form.name) }}</td>
                <td>{{ form_errors(form.name) }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ scenario.level }}</td>
                <td>{{ form_widget(form.level) }}</td>
                <td>{{ form_errors(form.level) }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ scenario.date ? scenario.date|date('d/m/Y') : '' }}</td>
                <td>{{ form_widget(form.date) }}</td>
                <td>{{ form_errors(form.date) }}</td>
            </tr>
            <tr>
                <th>Lien du post</th>
                <td>{{ scenario.postLink }}</td>
                <td>{{ form_widget(form.post_link) }}</td>
                <td>{{ form_errors(form.post_link) }}</td>
            </tr>
        </tbody>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Niveau</th>
                <th>Réussite</th>
                <th>Reputation</th>
                <th>Bonus Reputation</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% set mjToken = scenario.tokens|filter(token => token.type == 'MJ')|first %}
        {% if mjToken %}
            <tr>
                    <td>{{ mjToken.ownerUser.username }}</td>
                    <td></td>
                    <td>{{ mjToken.usageRate != 0 ? mjToken.usageRate ~ "% / " : "" }}{{ mjToken.totalRate }}%</td>
                    <td>{{ mjToken.deltaPr }}%</td>
                    <td>{{ "%+d"|format(mjToken.deltaPrFromLevel) }}%</td>
            </tr>
        {% endif %}
        {% for tokenForm in form.tokens %}
            
            {% set tokenData = tokenForm.vars.value %}
            {% if tokenData.type == "PJ" %}
                <tr>
                    <td>{{ tokenData.character.name }}</td>
                    <td>{{ tokenData.character.level }}</td>
                    
                    <td>{{ form_widget(tokenForm.totalRate) }}</td>
                    <td>{{ form_widget(tokenForm.delta_pr) }}</td>
                    <td>{{ "%+d"|format(tokenData.deltaPrFromLevel) }}%</td>
                    <td>        
                        <button type="submit" class="btn btn-primary btn-sm" 
                            name="removeToken" value="{{tokenData.id}}">Retirer</button>
                    </td>
                    
                </tr>
            {% else %}
                {{ form_widget(tokenForm.totalRate, {'attr': {'style': 'display: none;'}}) }}
                {{ form_widget(tokenForm.delta_pr, {'attr': {'style': 'display: none;'}}) }}
            {% endif %}    
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Niveau</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for character in characters %}
            <tr>
                <td>{{ character.name }}</td>
                <td>{{ character.level }}</td>
                <td>
                    <button type="submit" class="btn btn-primary btn-sm" 
                        name="addToken" value="{{character.id}}">Ajouter</button>
                </td>
            </tr>
                
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{{ form_end(form) }}

templates/scenario/_new_form.html.twig
    
{{ form_start(form) }}

    <table class="table">
        <tbody>
            <tr>
                <th>Name</th>
                <td>{{ form_widget(form.name) }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ form_widget(form.level) }}</td>
                <td>{{ form_errors(form.level) }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ form_widget(form.date) }}</td>
                <td>{{ form_errors(form.date) }}</td>
            </tr>
            <tr>
                <th>Post_link</th>
                <td>{{ form_widget(form.post_link) }}</td>
                <td>{{ form_errors(form.post_link) }}</td>
            </tr>
        </tbody>
    </table>

    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>

    {{ form_widget(form._token) }}

</form> 

templates/scenario/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Scenario{% endblock %}

{% block body %}
    
    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route, 'object' : scenario} )) }}

    {{ include('scenario/_edit_form.html.twig', {'button_label': 'Update'}) }}
{% endblock %}

templates/scenario/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Scenario index{% endblock %}

{% block body %}

    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route} )) }}

    <table class="table index">
        <thead>
            <tr>
                <th>Name</th>
                <th>Maitre de jeu</th>
                <th>Level</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        {% for scenario in scenarios %}
            <tr onclick="document.location = '{{ path('app_scenario_show', {'id': scenario.id}) }}';">
                <td>{{ scenario.name }}</td>
                <td>{{ scenario.gameMaster ? scenario.gameMaster.username  }}</td>
                <td>{{ scenario.level }}</td>
                <td>{{ scenario.date ? scenario.date|date('d/m/Y') : '' }}</td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/scenario/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Scenario{% endblock %}

{% block body %}

    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route} )) }}


    {{ include('scenario/_new_form.html.twig') }}

{% endblock %}

templates/scenario/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Scenario{% endblock %}

{% block body %}
    
    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route, 'object' : scenario} )) }}

    <table class="table">
        <tbody>
            <tr>
                <th>Name</th>
                <td>{{ scenario.name }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ scenario.level }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ scenario.date ? scenario.date|date('d/m/Y') : '' }}</td>
            </tr>
            <tr>
                <th>Lien du post</th>
                <td>{{ scenario.postLink }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ scenario.status }}</td>
                <td>
                    {% if scenario.status != "awarded" %}
                        <form action="{{ path("app_scenario_award", {'id': scenario.id}) }}" method="POST">
                                <button type="submit">Récompenser token</button>
                        </form>
                    {% endif %}
                </td>
            </tr>
        </tbody>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Niveau</th>
                <th>Réussite</th>
                <th>Reputation</th>
                <th>Bonus Reputation</th>
            </tr>
        </thead>
        <tbody>
        {% set mjToken = scenario.tokens|filter(token => token.type == 'MJ')|first %}
        {% if mjToken %}
            <tr>
                    <td>{{ mjToken.ownerUser.username }}</td>
                    <td></td>
                    <td>{{ mjToken.usageRate != 0 ? mjToken.usageRate ~ "% / " : "" }}{{ mjToken.totalRate }}%</td>
                    <td>{{ mjToken.deltaPr }}%</td>
                    <td>{{ "%+d"|format(mjToken.deltaPrFromLevel) }}%</td>
            </tr>
        {% endif %}
        {% for token in scenario.tokens %}
            {% if token.type == "PJ" %}
                <tr>
                    <td>{{ token.character is null ? "" : token.character.name}}</td>
                    <td>{{ token.character is null ? "" : token.character.level }}</td>
                    <td>{{ token.usageRate != 0 ? token.usageRate ~ "% / " : "" }}{{ token.totalRate }}%</td>
                    <td>{{ token.deltaPr }}%</td>
                    <td>{{ "%+d"|format(token.deltaPrFromLevel) }}%</td>
                </tr>
            {% endif %}
                
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}