src/Entity/Character.php
<?php

namespace App\Entity;


use App\Repository\CharacterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Get;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Entity(repositoryClass: CharacterRepository::class)]
    #[ApiResource(
        normalizationContext: ['groups' => ['owner:read']],
        stateless: false,
        operations: [
            // Permet l'affichage de la collection (GET /clients)
            new GetCollection(),
            // Permet l'affichage d'un seul élément (GET /clients/{id})
            new Get(),
        ],
    )]
class Character
{    
    public const LEVEL_UP = "levelUp";
    public const TRADE_PNJ = "tradePNJ";
    public const TRADE_PJ = "tradePJ";
    public const EDIT = "edit";
    public const NEW = "new";
    public const DELETE = "delete";
    public const CORRECTION = "correction";
    
    
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: false)]
    private ?string $name = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: false)]
    private ?string $title = null;

    #[ORM\Column(type: Types::BLOB, nullable: true)]
    private $img;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: false)]
    private ?int $level = 3;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 7, scale: 0, nullable: false)]
    private ?string $xp_current = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 7, scale: 0, nullable: false)]
    private ?string $xp_current_mj = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 8, scale: 2, nullable: false)]
    private ?string $gp = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: false)]
    private ?string $pr = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: false)]
    private ?\DateTime $end_activity = null;

    /**
     * @var Collection<int, Building>
     */
    #[ORM\OneToMany(targetEntity: Building::class, mappedBy: 'owner')]
    private Collection $buildings;

    /**
     * @var Collection<int, Activity>
     */
    #[ORM\OneToMany(targetEntity: Activity::class, mappedBy: 'participant')]
    private Collection $activities;


    #[ORM\ManyToOne(inversedBy: 'characters')]
    private ?User $owner = null;

    #[Groups(['owner:read'])]
    #[SerializedName('owner')]
    public function getOwnerId(): ?int
    {
        return $this->owner ? $this->owner->getId() : null;
    }

    /**
     * @var Collection<int, Token>
     */
    #[ORM\OneToMany(targetEntity: Token::class, mappedBy: 'character')]
    private Collection $tokens;

    private ?Token $consumableToken = null;

    /**
     * @var Collection<int, Scenario>
     */
    #[ORM\ManyToMany(targetEntity: Scenario::class, mappedBy: 'characters')]
    private Collection $scenarios;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_action_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $webhook_link = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $last_action = null;

    #[ORM\OneToOne(mappedBy: 'buyer', cascade: ['persist', 'remove'])]
    private ?CartGP $cartGP = null;

    /**
     * @var Collection<int, Item>
     */
    #[ORM\OneToMany(targetEntity: Item::class, mappedBy: 'owner')]
    private Collection $items;

    public function __construct()
    {
        $this->buildings = new ArrayCollection();
        $this->activities = new ArrayCollection();
        $this->tokens = new ArrayCollection();
        $this->scenarios = new ArrayCollection();
        $this->items = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getImg()
    {
        return $this->img;
    }

    public function setImg($img): static
    {
        $this->img = $img;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): static
    {
        $this->level = $level;

        return $this;
    }

    public function getXpCurrent(): ?string
    {
        return $this->xp_current;
    }

    public function setXpCurrent(string $xp_current): static
    {
        $this->xp_current = $xp_current;

        return $this;
    }

    public function getXpCurrentMj(): ?string
    {
        return $this->xp_current_mj;
    }

    public function setXpCurrentMj(string $xp_current_mj): static
    {
        $this->xp_current_mj = $xp_current_mj;

        return $this;
    }

    public function getGp(): ?string
    {
        return $this->gp;
    }

    public function setGp(string $gp): static
    {
        $this->gp = $gp;

        return $this;
    }

    public function getPr(): ?string
    {
        return $this->pr;
    }

    public function setPr(string $pr): static
    {
        $this->pr = $pr;

        return $this;
    }

    public function getEndActivity(): ?\DateTime
    {
        return $this->end_activity;
    }

    public function setEndActivity(?\DateTime $end_activity): static
    {
        $this->end_activity = $end_activity;

        return $this;
    }

    /**
     * @return Collection<int, Building>
     */
    public function getBuildings(): Collection
    {
        return $this->buildings;
    }

    public function addBuilding(Building $building): static
    {
        if (!$this->buildings->contains($building)) {
            $this->buildings->add($building);
            $building->setOwner($this);
        }

        return $this;
    }

    public function removeBuilding(Building $building): static
    {
        if ($this->buildings->removeElement($building)) {
            // set the owning side to null (unless already changed)
            if ($building->getOwner() === $this) {
                $building->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Activity>
     */
    public function getActivities(): Collection
    {
        return $this->activities;
    }

    public function addActivity(Activity $activity): static
    {
        if (!$this->activities->contains($activity)) {
            $this->activities->add($activity);
            $activity->setParticipant($this);
        }

        return $this;
    }

    public function removeActivity(Activity $activity): static
    {
        if ($this->activities->removeElement($activity)) {
            // set the owning side to null (unless already changed)
            if ($activity->getParticipant() === $this) {
                $activity->setParticipant(null);
            }
        }

        return $this;
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): static
    {
        $this->owner = $owner;

        return $this;
    }

    /**
     * @return Collection<int, Token>
     */
    public function getTokens(): Collection
    {
        return $this->tokens;
    }

    public function addToken(Token $token): static
    {
        if (!$this->tokens->contains($token)) {
            $this->tokens->add($token);
            $token->setCharacter($this);
        }

        return $this;
    }

    public function removeToken(Token $token): static
    {
        if ($this->tokens->removeElement($token)) {
            // set the owning side to null (unless already changed)
            if ($token->getCharacter() === $this) {
                $token->setCharacter(null);
            }
        }

        return $this;
    }

    public function setConsumableToken(?Token $token): static {
        $this->consumableToken = $token;

        return $this;
    }

    public function getConsumableToken(): ?Token {
        return $this->consumableToken;
    }

    /**
     * @return Collection<int, Scenario>
     */
    public function getScenarios(): Collection
    {
        return $this->scenarios;
    }

    public function addScenario(Scenario $scenario): static
    {
        if (!$this->scenarios->contains($scenario)) {
            $this->scenarios->add($scenario);
            $scenario->addCharacter($this);
        }

        return $this;
    }

    public function removeScenario(Scenario $scenario): static
    {
        if ($this->scenarios->removeElement($scenario)) {
            $scenario->removeCharacter($this);
        }

        return $this;
    }

    public function getLastActionDescription(): ?string
    {
        return $this->last_action_description;
    }

    public function setLastActionDescription(string $last_action_description): static
    {
        $this->last_action_description = $last_action_description;

        return $this;
    }

    public function getWebhookLink(): ?string
    {
        return $this->webhook_link;
    }

    public function setWebhookLink(?string $webhook_link): static
    {
        $this->webhook_link = $webhook_link;

        return $this;
    }

    public function getLastAction(): ?string
    {

src/Entity/Token.php
<?php

namespace App\Entity;

use App\Repository\TokenRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Get;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Entity(repositoryClass: TokenRepository::class)]
    #[ApiResource(
        normalizationContext: ['groups' => ['owner:read']],
        stateless: false,
        operations: [
            new GetCollection(),
            new Get(),
        ],
    )]
class Token
{
    public const STATUS_PUBLISHED = 'created';
    public const STATUS_AWARDED = 'awarded';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;
    
    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: false)]
    private ?string $type = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?int $usage_rate = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?int $delta_pr = null;

    #[Groups(['owner:read'])]
    private ?int $delta_pr_from_level = null;

    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?Scenario $scenario = null;

    #[Groups(['owner:read'])]
    #[SerializedName('scenario')]
    public function getScenarioId(): ?int
    {
        return $this->scenario ? $this->scenario->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?Character $character = null;

    #[Groups(['owner:read'])]
    #[SerializedName('character')]
    public function getCharacterId(): ?int
    {
        return $this->character ? $this->character->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?\DateTime $date_of_reception = null;

    #[Groups(['owner:read'])]
    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?User $owner_user = null;

    #[Groups(['owner:read'])]
    #[SerializedName('owner_user')]
    public function getOwnerId(): ?int
    {
        return $this->owner_user ? $this->owner_user->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $totalRate = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $totalPr = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getUsageRate(): ?int
    {
        return $this->usage_rate;
    }

    public function setUsageRate(int $usage_rate): static
    {
        $this->usage_rate = $usage_rate;

        return $this;
    }

    public function getDeltaPr(): ?int
    {
        return $this->delta_pr;
    }

    public function setDeltaPr(int $delta_pr): static
    {
        $this->delta_pr = $delta_pr;

        return $this;
    }

    public function getDeltaPrFromLevel(): ?int
    {
        return $this->delta_pr_from_level;
    }

    public function setDeltaPrFromLevel(int $delta_pr_from_level): static
    {
        $this->delta_pr_from_level = $delta_pr_from_level;

        return $this;
    }

    public function getScenario(): ?Scenario
    {
        return $this->scenario;
    }

    public function setScenario(?Scenario $scenario): static
    {
        $this->scenario = $scenario;

        return $this;
    }

    public function getCharacter(): ?Character
    {
        return $this->character;
    }

    public function setCharacter(?Character $character): static
    {
        $this->character = $character;

        return $this;
    }

    public function getDateOfReception(): ?\DateTime
    {
        return $this->date_of_reception;
    }

    public function setDateOfReception(\DateTime $date_of_reception): static
    {
        $this->date_of_reception = $date_of_reception;

        return $this;
    }

    public function getOwnerUser(): ?User
    {
        return $this->owner_user;
    }

    public function setOwnerUser(?User $owner_user): static
    {
        $this->owner_user = $owner_user;

        return $this;
    }

    public function getTotalRate(): ?string
    {
        return $this->totalRate;
    }

    public function setTotalRate(string $totalRate): static
    {
        $this->totalRate = $totalRate;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getTotalPr(): ?string
    {
        return $this->totalPr;
    }

    public function setTotalPr(?string $totalPr): static
    {
        $this->totalPr = $totalPr;

        return $this;
    }
}

src/Form/CharacterType.php
<?php

namespace App\Form;

use App\Entity\Character;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CharacterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
            ->add('title')
            ->add('pr')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Character::class,
        ]);
    }
}

templates/character/_delete_form.html.twig
<form method="post" action="{{ path('app_character_delete', {'id': character.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ character.id) }}">
    <button class="btn">Delete</button>
</form>

templates/character/_edit_form.html.twig
{{ form_start(form) }}
    {% set characterData = form.vars.value %}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ "%04d"|format(characterData.id) }}</td>
            </tr>
            <tr>
                <th>Propriétaire</th>
                <td>{{ characterData.owner.username }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ characterData.name }}</td>
                <td>{{ form_widget(form.name) }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ characterData.title }}</td>
                <td>{{ form_widget(form.title) }}</td>
            </tr>
            <tr>
                <th>Niveau</th>
                <td  class="fixed-width-value">{{ "%7d"|format(characterData.level) }}</td>
            </tr>
            <tr>
                <th>XP joueur</th>
                <td class="fixed-width-value">{{ "%7d"|format(characterData.xpCurrent) }} XP</td>
                <td class="fixed-width-value">/ {{ "%7d"|format((XPNiveauSuivant - totalXP)) }} XP</td>
            </tr>
            <tr>
                <th>Dont XP maitrise</th>
                <td class="fixed-width-value">{{ "%7d"|format(characterData.xpCurrentMj) }} XP</td>
                <td class="fixed-width-value">/ {{ "%7d"|format((XPNiveauSuivant - totalXP)/2) }} XP</td>
            </tr>
            <tr>
                <th>Richesse</th>
                <td class="fixed-width-value">{{ "%7d"|format(characterData.gp) }} GP</td>
                <td>{{ form_widget(form.gp_add) }} GP</td>
                <td class="fixed-width-value">/ {{ "%7d"|format(GV) }} GV</td>
            </tr>
            <tr>
                <th>Reputation</th>
                <td class="fixed-width-value">{{ "%7d"|format(characterData.pr) }} PR</td>
                <td>{{ form_widget(form.pr_add) }} PR</td>
            </tr>
            <tr>
                <th>Fin d'activité</th>
                {% if characterData.endActivity|date('d/m/Y') > date('now')|date('d/m/Y') %}
                        <td>{{ characterData.endActivity | date('d/m/Y') }}</td>
                {% else  %}
                        <td>Disponible</td>
                {% endif %}
                <td>{{ form_widget(form.activity_add) }} jours</td>
            </tr>
            <tr>
                <th>Webhook</th>
                <td>{{ characterData.webhookLink ? 'Renseigné' : 'Non Renseigné' }}</td>
            </tr>
            {# 
            <tr>
                <th>Type correction</th>
                <td colspan="3">{{ form_widget(form.last_action) }}</td>
            </tr>
            #}
            <tr>
                <th>Description</th>
                <td colspan="3">{{ form_widget(form.last_action_description) }}</td>
            </tr>
        </tbody>
    </table>


    <div class="form-group">
    </div>
    
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    
    <table class="table">
        <thead>
            <tr>
                <th>Champ</th>
                <th></th>
                <th>Ancienne valeur</th>
                <th></th>
                <th>Nouvelle valeur</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for log in logs %}
            {% for key, diff in log.diffs %}
                {% if key != 'last_action_description' and key != 'webhook_link' and key != 'last_action'  %}
                    <tr>
                        <td colspan="2">{{ key }}</td>
                        <td colspan="2">
                            {% if diff.old is defined %}
                                {% if diff.old.id is defined %}
                                    {{ diff.old.id }}
                                {% else %}
                                    {{ diff.old }}
                                {% endif %}
                            {% endif %}
                        </td>
                        <td colspan="2">
                            {% if diff.new is defined %}
                                {% if diff.new.id is defined %}
                                    {{ diff.new.id }}
                                {% else %}
                                    {{ diff.new }}
                                {% endif %}
                            {% endif %}
                        </td>

                    </tr>
                {% endif %}
            {% endfor %}
            <tr>
                <td colspan="2">Description :
                    {{ log.diffs['last_action_description'] is defined ? 
                        log.diffs['last_action_description'].new : "Description vide !" }}
                </td>
                <td colspan="2">le {{ log.createdAt | date('d/m/Y h:m:s') }}</td>
                <td colspan="2">par {{ log.username }}</td>
            </tr>
            <tr>
                <td></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {{ form_widget(form._token) }}
    
</form>

templates/character/_new_form.html.twig
{{ form_start(form) }}

    <table class="table">
        <tbody>
            <tr>
                <th>
                    Nom
                </th>
                <td>{{ form_widget(form.name) }}</td>
                <td>{{ form_errors(form.name) }}</td>
            </tr>
            <tr>
                <th>
                Titre
                </th>
                <td>{{ form_widget(form.title) }}</td>
                <td>{{ form_errors(form.title) }}</td>
            </tr>
            <tr>
                <th>
                Niveau
                </th>
                <td>3</td>
            </tr>
            <tr>
                <th>Richesse</th>
                <td>3750 GP</td>
            </tr>
            <tr>
                <th>
                <i class="fa-solid fa-circle-info"
                    style="cursor:pointer;"
                    title="1500, ou 500 avec le trait Gaijin"></i>
                Reputation
                </th>
                <td>{{ form_widget(form.pr) }} PR</td>
                <td>{{ form_errors(form.pr) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="form-group">
    </div>
    
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
    
    {{ form_widget(form._token) }}
    
</form> 

templates/character/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Character index{% endblock %}

{% block body %}

    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route} )) }}

    <table class="table index">
        <thead>
            <tr>
                <th>Id</th>
                <th>Joueur</th>
                <th>Nom</th>
                <th>Titre</th>
                <th>Niveau</th>
                <th>Réputation</th>
                <th>End_activity</th>
            </tr>
        </thead>
        <tbody>
        {% for character in characters %}
            <tr onclick="document.location = '{{ path('app_character_show', {'id': character.id}) }}';">
                <td>{{ "%04d"|format(character.id) }}</td>
                <td>{{ character.owner.id ?? ""}}</td>
                <td>{{ character.name }}</td>
                <td>{{ character.title }}</td>
                <td>{{ character.level }}</td>
                <td class="fixed-width-value">{{ "%7d"|format(character.pr) }} PR</td>

                {% if character.endActivity|date('d/m/Y') > date('now')|date('d/m/Y') %}
                    <td>{{ character.endActivity | date('d/m/Y') }}</td>
                {% else  %}
                    <td>Disponible</td>
                {% endif %}

            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/character/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Character{% endblock %}

{% block body %}

    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route, 'object' : character} )) }}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ "%04d"|format(character.id) }}</td>
            </tr>
            <tr>
                <th>Propriétaire</th>
                <td>{{ character.owner.username }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ character.name }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ character.title }}</td>
            </tr>
            <tr>
                <th>Niveau</th>
                <td  class="fixed-width-value">{{ "%7d"|format(character.level) }}</td>  
                {% if (totalXP + character.xpCurrent) >= XPNiveauSuivant %}
                    <td>
                        <form action="{{ path("app_character_level_up", {'id': character.id}) }}" method="POST">
                            <button type="submit" class="btn btn-primary btn-sm">
                                    Passer un niveau
                            </button>
                        </form>
                    </td>
                {% endif %}
            </tr>
            <tr>
                <th>XP total</th>
                <td class="fixed-width-value">{{ "%7d"|format(totalXP + character.xpCurrent) }} XP</td>
                <td class="fixed-width-value">/ {{ "%7d"|format(XPNiveauSuivant) }} XP</td>
            </tr>
            <tr>
                <th>XP actuel</th>
                <td class="fixed-width-value">{{ "%7d"|format(character.xpCurrent) }} XP</td>
                <td class="fixed-width-value">/ {{ "%7d"|format(XPNiveauSuivant - totalXP) }} XP</td>
            </tr>
            <tr>
                <th>Dont XP maitrise</th>
                <td class="fixed-width-value">{{ "%7d"|format(character.xpCurrentMj) }} XP</td>
                <td class="fixed-width-value">/ {{ "%7d"|format((XPNiveauSuivant - totalXP)/2) }} XP</td>
            </tr>
            <tr>
                <th>Richesse</th>
                <td class="fixed-width-value">{{ "%7d"|format(character.gp) }} GP</td>
                <td class="fixed-width-value">/ {{ "%7d"|format(GV) }} GV</td>
                {#
                <td>
                    <form action="{{ path("app_character_cart_gp", {'id': character.id}) }}" method="GET">
                        <button type="submit" class="btn btn-primary btn-sm">
                            Acheter en GV
                        </button>
                    </form>
                </td>
                #}
            </tr>
            <tr>
                <th>Reputation</th>
                <td class="fixed-width-value">{{ "%7d"|format(character.pr) }} PR</td>
            </tr>
            <tr>
                <th>Fin d'activité</th>

            {% if character.endActivity|date('d/m/Y') > date('now')|date('d/m/Y') %}
                    <td>{{ character.endActivity | date('d/m/Y') }}</td>
            {% else  %}
                    <td>Disponible</td>
            {% endif %}
            </tr>
            <tr>
                <th>Webhook</th>
                <td>{{ character.webhookLink ? 'Renseigné' : 'Non Renseigné' }}</td>
            </tr>
        </tbody>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Nom Token</th>
                <th>Type</th>
                <th>Taux</th>
                <th>Reputation</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for token in character.tokens|sort((a, b) => a.dateOfReception <=> b.dateOfReception) %}
            {% if token.status == "awarded" %}
                <tr>
                    <td>{{ token.name }}</td>
                    <td>{{ token.type }}</td>
                    <td>{{ token.usageRate }} % / {{ token.totalRate }} %</td>
                    <td>{{ token.totalPr }} %</td>
                    <td>{{ token.dateOfReception|date('d/m/Y H:i', 'GMT+1') }}</td>
                    
                    {% if token == character.consumableToken %}
                        <td>
                            <form action="{{ path("app_character_consume", {'id': character.id}) }}" method="POST">
                                <button type="submit"
                                        class="btn btn-primary btn-sm">
                                        Consommer
                                </button>
                            </form>
                        </td>
                    {% endif %}
                </tr>
            {% endif %}
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <table class="table">
        <thead>
            <tr>
                <th>Champ</th>
                <th></th>
                <th>Ancienne valeur</th>
                <th></th>
                <th>Nouvelle valeur</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for log in logs %}
            {% for key, diff in log.diffs %}
                {% if key != 'last_action_description' and key != 'webhook_link' and key != 'last_action' %}
                    <tr>
                        <td colspan="2">{{ key }}</td>
                        <td colspan="2">
                            {% if diff.old is defined %}
                                {% if diff.old.id is defined %}
                                    {{ diff.old.id }}
                                {% else %}
                                    {{ diff.old }}
                                {% endif %}
                            {% endif %}
                        </td>
                        <td colspan="2">
                            {% if diff.new is defined %}
                                {% if diff.new.id is defined %}
                                    {{ diff.new.id }}
                                {% else %}
                                    {{ diff.new }}
                                {% endif %}
                            {% endif %}
                        </td>

                    </tr>
                {% endif %}
            {% endfor %}
            <tr>
                <td colspan="2">Description :
                    {{ log.diffs['last_action_description'] is defined ? 
                        log.diffs['last_action_description'].new : "Description vide !" }}
                </td>
                <td colspan="2">le {{ log.createdAt | date('d/m/Y h:m:s') }}</td>
                <td colspan="2">par {{ log.username }}</td>
            </tr>
            <tr>
                <td></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}