src/Entity/Activity.php
<?php

namespace App\Entity;

use App\Repository\ActivityRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ActivityRepository::class)]
class Activity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column]
    private ?\DateTime $date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 8, scale: 2, nullable: true)]
    private ?string $cost_gp = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $cost_pr = null;

    #[ORM\Column(nullable: true)]
    private ?int $duration = null;

    #[ORM\Column(length: 1000)]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'activities')]
    private ?Character $participant = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getDate(): ?\DateTime
    {
        return $this->date;
    }

    public function setDate(\DateTime $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getCostGp(): ?string
    {
        return $this->cost_gp;
    }

    public function setCostGp(?string $cost_gp): static
    {
        $this->cost_gp = $cost_gp;

        return $this;
    }

    public function getCostPr(): ?string
    {
        return $this->cost_pr;
    }

    public function setCostPr(?string $cost_pr): static
    {
        $this->cost_pr = $cost_pr;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): static
    {
        $this->duration = $duration;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getParticipant(): ?Character
    {
        return $this->participant;
    }

    public function setParticipant(?Character $participant): static
    {
        $this->participant = $participant;

        return $this;
    }
}

src/Form/ActivityType.php
<?php

namespace App\Form;

use App\Entity\Activity;
use App\Entity\Character;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActivityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type')
            ->add('date')
            ->add('cost_gp')
            ->add('cost_pr')
            ->add('duration')
            ->add('description')
            ->add('participant', EntityType::class, [
                'class' => Character::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Activity::class,
        ]);
    }
}

src/Controller/ActivityController.php
<?php

namespace App\Controller;

use App\Entity\Activity;
use App\Form\ActivityType;
use App\Repository\ActivityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/activity')]
final class ActivityController extends AbstractController
{
    #[Route(name: 'app_activity_index', methods: ['GET'])]
    public function index(ActivityRepository $activityRepository): Response
    {
        return $this->render('activity/index.html.twig', [
            'activities' => $activityRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_activity_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $activity = new Activity();
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($activity);
            $entityManager->flush();

            return $this->redirectToRoute('app_activity_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('activity/new.html.twig', [
            'activity' => $activity,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_activity_show', methods: ['GET'])]
    public function show(Activity $activity): Response
    {
        return $this->render('activity/show.html.twig', [
            'activity' => $activity,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_activity_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Activity $activity, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ActivityType::class, $activity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_activity_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('activity/edit.html.twig', [
            'activity' => $activity,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_activity_delete', methods: ['POST'])]
    public function delete(Request $request, Activity $activity, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$activity->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($activity);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_activity_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/activity/_delete_form.html.twig
<form method="post" action="{{ path('app_activity_delete', {'id': activity.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ activity.id) }}">
    <button class="btn">Delete</button>
</form>

templates/activity/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Activity{% endblock %}

{% block body %}
    <h1>Edit Activity</h1>

    {{ include('activity/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_activity_index') }}">back to list</a>

    {{ include('activity/_delete_form.html.twig') }}
{% endblock %}

templates/activity/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity index{% endblock %}

{% block body %}
    <h1>Activity index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Date</th>
                <th>Cost_gp</th>
                <th>Cost_pr</th>
                <th>Duration</th>
                <th>Description</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for activity in activities %}
            <tr>
                <td>{{ activity.id }}</td>
                <td>{{ activity.type }}</td>
                <td>{{ activity.date ? activity.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ activity.costGp }}</td>
                <td>{{ activity.costPr }}</td>
                <td>{{ activity.duration }}</td>
                <td>{{ activity.description }}</td>
                <td>
                    <a href="{{ path('app_activity_show', {'id': activity.id}) }}">show</a>
                    <a href="{{ path('app_activity_edit', {'id': activity.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_activity_new') }}">Create new</a>
{% endblock %}

templates/activity/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Activity{% endblock %}

{% block body %}
    <h1>Create new Activity</h1>

    {{ include('activity/_form.html.twig') }}

    <a href="{{ path('app_activity_index') }}">back to list</a>
{% endblock %}

templates/activity/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Activity{% endblock %}

{% block body %}
    <h1>Activity</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ activity.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ activity.type }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ activity.date ? activity.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Cost_gp</th>
                <td>{{ activity.costGp }}</td>
            </tr>
            <tr>
                <th>Cost_pr</th>
                <td>{{ activity.costPr }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ activity.duration }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ activity.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_activity_index') }}">back to list</a>

    <a href="{{ path('app_activity_edit', {'id': activity.id}) }}">edit</a>

    {{ include('activity/_delete_form.html.twig') }}
{% endblock %}