src/Entity/Token.php
<?php

namespace App\Entity;

use App\Repository\TokenRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Get;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Entity(repositoryClass: TokenRepository::class)]
    #[ApiResource(
        normalizationContext: ['groups' => ['owner:read']],
        stateless: false,
        operations: [
            new GetCollection(),
            new Get(),
        ],
    )]
class Token
{
    public const STATUS_PUBLISHED = 'created';
    public const STATUS_AWARDED = 'awarded';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $name = null;
    
    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: false)]
    private ?string $type = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?int $usage_rate = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?int $delta_pr = null;

    #[Groups(['owner:read'])]
    private ?int $delta_pr_from_level = null;

    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?Scenario $scenario = null;

    #[Groups(['owner:read'])]
    #[SerializedName('scenario')]
    public function getScenarioId(): ?int
    {
        return $this->scenario ? $this->scenario->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?Character $character = null;

    #[Groups(['owner:read'])]
    #[SerializedName('character')]
    public function getCharacterId(): ?int
    {
        return $this->character ? $this->character->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\Column(nullable: true)]
    private ?\DateTime $date_of_reception = null;

    #[Groups(['owner:read'])]
    #[ORM\ManyToOne(inversedBy: 'tokens')]
    private ?User $owner_user = null;

    #[Groups(['owner:read'])]
    #[SerializedName('owner_user')]
    public function getOwnerId(): ?int
    {
        return $this->owner_user ? $this->owner_user->getId() : null;
    }

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $totalRate = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 0, nullable: true)]
    private ?string $totalPr = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getUsageRate(): ?int
    {
        return $this->usage_rate;
    }

    public function setUsageRate(int $usage_rate): static
    {
        $this->usage_rate = $usage_rate;

        return $this;
    }

    public function getDeltaPr(): ?int
    {
        return $this->delta_pr;
    }

    public function setDeltaPr(int $delta_pr): static
    {
        $this->delta_pr = $delta_pr;

        return $this;
    }

    public function getDeltaPrFromLevel(): ?int
    {
        return $this->delta_pr_from_level;
    }

    public function setDeltaPrFromLevel(int $delta_pr_from_level): static
    {
        $this->delta_pr_from_level = $delta_pr_from_level;

        return $this;
    }

    public function getScenario(): ?Scenario
    {
        return $this->scenario;
    }

    public function setScenario(?Scenario $scenario): static
    {
        $this->scenario = $scenario;

        return $this;
    }

    public function getCharacter(): ?Character
    {
        return $this->character;
    }

    public function setCharacter(?Character $character): static
    {
        $this->character = $character;

        return $this;
    }

    public function getDateOfReception(): ?\DateTime
    {
        return $this->date_of_reception;
    }

    public function setDateOfReception(\DateTime $date_of_reception): static
    {
        $this->date_of_reception = $date_of_reception;

        return $this;
    }

    public function getOwnerUser(): ?User
    {
        return $this->owner_user;
    }

    public function setOwnerUser(?User $owner_user): static
    {
        $this->owner_user = $owner_user;

        return $this;
    }

    public function getTotalRate(): ?string
    {
        return $this->totalRate;
    }

    public function setTotalRate(string $totalRate): static
    {
        $this->totalRate = $totalRate;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getTotalPr(): ?string
    {
        return $this->totalPr;
    }

    public function setTotalPr(?string $totalPr): static
    {
        $this->totalPr = $totalPr;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Get;

#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_DISCORD_ID', fields: ['discord_id'])]
#[UniqueEntity(fields: ['discord_id'], message: 'There is already an account with this discord_id')]
#[ORM\Entity(repositoryClass: UserRepository::class)]
    #[ApiResource(
        normalizationContext: ['groups' => ['owner:read']],
        stateless: false,
        operations: [
            // Permet l'affichage de la collection (GET /clients)
            new GetCollection(),
            // Permet l'affichage d'un seul élément (GET /clients/{id})
            new Get(),
        ],
    )]class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;


    #[ORM\Column(length: 180)]
    private ?string $discord_id = null;

    #[Groups(['owner:read'])]
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $username = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $role = null;

    #[Groups(['owner:read'])]
    #[ORM\Column]
    private ?int $nb_character_max = 1;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    /**
     * @var Collection<int, Character>
     */
    #[ORM\OneToMany(targetEntity: Character::class, mappedBy: 'owner')]
    private Collection $characters;

    /**
     * @var Collection<int, Scenario>
     */
    #[ORM\OneToMany(targetEntity: Scenario::class, mappedBy: 'game_master')]
    private Collection $scenarios;

    /**
     * @var Collection<int, Token>
     */
    #[ORM\OneToMany(targetEntity: Token::class, mappedBy: 'owner_user')]
    private Collection $tokens;

    public function __construct()
    {
        $this->characters = new ArrayCollection();
        $this->scenarios = new ArrayCollection();
        $this->tokens = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->username;
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    
    public function getDiscordId(): ?string
    {
        return $this->discord_id;
    }

    public function setDiscordId(string $discord_id): static
    {
        $this->username = $discord_id;
        $this->discord_id = $discord_id;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getRole(): ?string
    {
        return $this->role;
    }

    public function setRole(string $role): static
    {
        $this->role = $role;

        return $this;
    }

    public function getNbCharacterMax(): ?int
    {
        return $this->nb_character_max;
    }

    public function setNbCharacterMax(int $nb_character_max): static
    {
        $this->nb_character_max = $nb_character_max;

        return $this;
    }

    /**
     * @return Collection<int, Character>
     */
    public function getCharacters(): Collection
    {
        return $this->characters;
    }

    public function addCharacter(Character $character): static
    {
        if (!$this->characters->contains($character)) {
            $this->characters->add($character);
            $character->setOwner($this);
        }

        return $this;
    }

    public function removeCharacter(Character $character): static
    {
        if ($this->characters->removeElement($character)) {
            // set the owning side to null (unless already changed)
            if ($character->getOwner() === $this) {
                $character->setOwner(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Scenario>
     */
    public function getScenarios(): Collection
    {
        return $this->scenarios;
    }

    public function addScenario(Scenario $scenario): static
    {
        if (!$this->scenarios->contains($scenario)) {
            $this->scenarios->add($scenario);
            $scenario->setGameMaster($this);
        }

        return $this;
    }

    public function removeScenario(Scenario $scenario): static
    {
        if ($this->scenarios->removeElement($scenario)) {
            // set the owning side to null (unless already changed)
            if ($scenario->getGameMaster() === $this) {
                $scenario->setGameMaster(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Token>
     */
    public function getTokens(): Collection
    {
        return $this->tokens;
    }

    public function addToken(Token $token): static
    {
        if (!$this->tokens->contains($token)) {
            $this->tokens->add($token);
            $token->setOwnerUser($this);
        }

        return $this;
    }

    public function removeToken(Token $token): static
    {
        if ($this->tokens->removeElement($token)) {
            // set the owning side to null (unless already changed)
            if ($token->getOwnerUser() === $this) {
                $token->setOwnerUser(null);
            }
        }

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->discord_id;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Ensure the session doesn't contain actual password hashes by CRC32C-hashing them, as supported since Symfony 7.3.
     */
    public function __serialize(): array
    {
        $data = (array) $this;
        $data["\0".self::class."\0password"] = hash('crc32c', $this->password);

        return $data;
    }

    #[\Deprecated]
    public function eraseCredentials(): void
    {
        // @deprecated, to be removed when upgrading to Symfony 8
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\Token;
use App\Entity\User;
use Doctrine\Common\Collections\Criteria;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('tokens', CollectionType::class, [
                'entry_type' => MJListedTokenType::class,
                'entry_options' => ['label' => false],
                'data' => $builder->getData()
                    ?->getTokens()?->matching(
                        Criteria::create()->where(Criteria::expr()->eq('status', Token::STATUS_AWARDED))
            )
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[Route('/')]
final class UserController extends AbstractController
{
    #[Route(name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[IsGranted('edit', subject: 'user'), Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_user_edit', ['id' => $user->getId()]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[IsGranted('delete', subject: 'user'), Route('/{id}', name: 'app_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('app_user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form) }}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles|join('/')|replace({'ROLE_': ''}) }}</td>
            </tr>
            <tr>
                <th>Nombre de personnages</th>
                <td> {{ user.characters.count }} </td>
                <td>/ {{ user.nbCharacterMax }}</td>
            </tr>
        </tbody>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Personnage</th>
                <th>Réussite</th>
                <th>Date d'attribution</th>
            </tr>
        </thead>
        <tbody>
        {% for tokenForm in form.tokens %}
            {% set tokenData = tokenForm.vars.value %}
            {% if tokenData.status == "awarded" %}
                <tr>
                    <td>{{ tokenData.name }}</td>
                    {% if tokenData.character is not null %}
                        <td>{{ form_widget(tokenForm.character, {'attr': {'style': 'display: none;'}}) }} {{ tokenData.character.name }}</td>
                    {% else %}
                        <td>{{ form_widget(tokenForm.character) }}</td>
                    {% endif %}
                    <td>{{ tokenData.usageRate }} % / {{ tokenData.totalRate }} %</td>
                    <td>{{ tokenData.totalPr }} %</td>
                    <td>{{ tokenData.dateOfReception is not null ? tokenData.dateOfReception|date('d/m/Y H:i', 'GMT+1') : '' }}</td>
                    <td></td>
                </tr>
            {% endif %}
        {% else %}
            <tr>
                <td colspan="11">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <button type="submit" class="btn btn-primary btn-sm">Update</button>

    {{ form_widget(form._token) }}
{{ form_end(form, {'render_rest': false}) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}

    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route, 'object' : user} )) }}

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}

    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route} )) }}

    <table class="table index">
        <thead>
            <tr>
                <th>Username</th>
                <th>Personnages</th>
                <th>Personnage principal</th>
                <th>Scénarios maitrisé</th>
                <th>Scénarios joués</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr onclick="document.location = '{{ path('app_user_show', {'id': user.id}) }}';">
                <td>{{ user.username }}</td>
                <td> {{ user.characters.count }} / {{ user.nbCharacterMax }} </td>
                <td></td>
                <td>{{ user.scenarios.count }}</td>
                <td></td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h2>Create new User</h2>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('app_user_index') }}">back to list</a>
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}

    {% set current_route = app.request.attributes.get('_route') %}
    {{ render(controller('App\\Controller\\ActionController::index',{'route' : current_route, 'object' : user} )) }}

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ user.id }}</td>
            </tr>
            <tr>
                <th>Pseudo</th>
                <td>{{ user.username }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ user.roles|join('/')|replace({'ROLE_': ''}) }}</td>
            </tr>
            <tr>
                <th>Nombre de personnages</th>
                <td> {{ user.characters.count }} </td>
                <td>/ {{ user.nbCharacterMax }}</td>
            </tr>
        </tbody>
    </table>

    <table class="table">
        <thead>
            <tr>
                <th>Nom Token</th>
                <th>Type</th>
                <th>Taux</th>
                <th>Pr</th>
                <th>Date</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for token in user.tokens %}
            {% if token.status == "awarded" %}
                <tr>
                    <td>{{ token.name }}</td>
                    <td>{{ token.character != null ? token.character.name : "" }}</td>
                    <td>{{ token.usageRate }} % / {{ token.totalRate }} %</td>
                    <td>{{ token.totalPr }}</td>
                    <td>{{ token.dateOfReception is not null ? token.dateOfReception|date('d/m/Y H:i', 'GMT+1') : '' }}</td>
                    <td></td>
                </tr>
            {% endif %}
            {% else %}
                <tr>
                    <td colspan="4">no records found</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}